'use client';
import { Inter } from "next/font/google";
import "@/css/style.css";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Belanja Bersama UMKN Indonesia",
//   description: "Generated by create next app",
//   openGraph: {
//     title: "Belanja Bersama UMKN Indonesia",
//     description: "Generated by create next app",
//     image: "/assets/images/static/nusan.svg",
//     type: "website",
//     url: "https://belanja-bersama-umkn.vercel.app/",
//     siteName: "Belanja Bersama UMKN Indonesia",
//   }
// };
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Belanja Bersama UMKN Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/images/static/nusan.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta property="og:title" content="Belanja Bersama UMKN Indonesia" />
        <meta property="og:description" content="Generated by create next app" />
        <meta property="og:image" content="/assets/images/static/nusan.svg" />
        <meta property="og:url" content="https://belanja-bersama-umkn.vercel.app/" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Belanja Bersama UMKN Indonesia" />
        <meta property="og:locale" content="id_ID" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:type" content="image/png" />
        <meta property="fb:app_id" content="123" />
        <meta name="twitter:card" content="summary_large_image" />
      </head>
      <body className={`${inter.className} bg-white`}>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
