import { Inter } from "next/font/google";
import "@/css/style.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Belanja Bersama UMKN Indonesia",
  description: "Generated by create next app",
  openGraph: {
    title: "Belanja Bersama UMKN Indonesia",
    description: "Generated by create next app",
    image: "/assets/images/static/nusan.svg",
    type: "website",
    url: "https://belanja-bersama-umkn.vercel.app/",
    siteName: "Belanja Bersama UMKN Indonesia",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>{children}</body>
    </html>
  );
}
