import Ecommers from "@/components/Ecomers";
import DasLayouts from "@/components/Layouts/DasLayouts";
import Navbar from "@/components/Navbar";
import { Metadata } from "next";

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}
export default function Dashboard() {
  return (
    <DasLayouts>
      <Ecommers />
    </DasLayouts>
  )
}


